#!/bin/bash -e

ORG_PATH="github.com/appc"
REPO_PATH="${ORG_PATH}/abd"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

eval $(go env)

go build -o bin/abd ${REPO_PATH}
for strategy in io.abd.https-dns io.abd.local io.abd.nfs io.abd.noop; do
	go build -o bin/${strategy} ${REPO_PATH}/strategies/${strategy}
done
